implemented upload_geometry() function
USDA-SCINet/pygcdl pull request #1
Opened 2023-12-06 22:05 UTC by NoaMillsUSDA-ARS

Accepts geojson, shp, csv, and zip files.

2023-12-08 16:15 UTC, HeatherSavoy-USDA commented
Thanks! I have two small comments about method names:

1. I think when we were discussing rgeocdl and pygcdl function/method names, we did agree on underscores like you implemented, but I think we also said that "getDatasetInfo" sounded more informative than "view_metadata". So can we do "get_dataset_info"? (We can do another PR for rgeocdl to make it match.)
2. The getDatasets() and getDatasetInfo() in client_example.py should then be updated.

2023-12-11 15:38 UTC, BrianStucky-USDA commented
I agree with both of Heather's comments! I have a few additional comments, too.

First some coding style suggestions:
* Your new code uses tabs for indentation, but we use spaces (4 spaces per indentation level) throughout GeoCDL. Please configure your editor to use spaces instead of tabs, as this is the standard community practice for Python code and also [recommended by](https://peps.python.org/pep-0008/#indentation) [PEP 8](https://peps.python.org/pep-0008/#tabs-or-spaces).
* Comments should include a space after the `#` and should usually be complete sentences, again, per [PEP 8](https://peps.python.org/pep-0008/#comments).
* I typically limit line lengths to 80 characters. This more or less follows [the PEP 8 recommendations](https://peps.python.org/pep-0008/#maximum-line-length) and generally makes code more readable (IMO).
* Using blank lines to separate logical sections of code can really help with readability, too.
* Functions should include a docstring that describes the function semantics and interface.
* `=` for a keyword argument in a function call should not have spaces next to it; again, per [PEP 8](https://peps.python.org/pep-0008/#pet-peeves).

And then four other comments:
* Creating a temporary directory for staging the ZIP file contents should use a `TemporaryDirectory` object from the [tempfile](https://docs.python.org/3/library/tempfile.html) module. `TemporaryDirectory` should be used as a context manager. This will ensure that:
  * The temporary directory is created in the proper, OS-specific location.
  * All files are cleaned up even if an exception occurs during processing.
* There are what appear to be debug `print()` statements in the code that should be removed.
* `shx_file_path` is created but the path is never validated.
* You might consider using the newer [pathlib](https://docs.python.org/3/library/pathlib.html) filesystem interface instead of the older `os.path` methods. The former provides better abstractions and more readable code (IMO).

2023-12-11 17:30 UTC, BrianStucky-USDA commented
I just now pushed [a commit](86b3cadf51f53c25aee39fcce4516399a6ce000f) that gives an example of how I might format the code and comments you added. I hope that helps!

2024-01-04 04:04 UTC, HeatherSavoy-USDA requested changes
I'm trying out this review feature for the first time! 🎉

2024-01-04 04:04 UTC, HeatherSavoy-USDA commented on pygcdl.py
> +                spatial_subset += "&geom_guid" + geom[i]
Is this concatenating multiple GUIDs together in one string?

2024-01-04 04:04 UTC, HeatherSavoy-USDA commented on pygcdl.py
> +                spatial_subset += "&geom_guid" + geom[i]
Missing = in "&geom_guid"

2024-01-04 04:04 UTC, HeatherSavoy-USDA commented on README.md
> +To run the script client_example.py, you must first unzip the sample datafiles, ie:
The examples should be as simple to use as possible. If you want to stick to these counties, you could strip all (or most) attributes, transform the geometries to EPSG:4326 (if they aren't in the CRS already), and save the result as geojson here instead. Then they would each be a single file with no unzipping needed and less unnecessary data included.

2024-05-02 23:36 UTC, NoaMillsUSDA-ARS commented
Outdated PR

2024-05-02 23:36 UTC, closed without merging